.TH nest 1 "26 November 2019" "version 1.0"

.SH NAME

." Bold acronym letters
nest - 
.BR Ne twork
.BR S tack
.BR T ester

.SH SYNOPSIS

." Update synopsis as and when new features are added.
." Currently dummy options are included.
.B nest
.B [-a] [-b] [-f
.I filename
.B ]

.SH DESCRIPTION

." TODO: Add appropriate description for the tool.
This is the description for
.B nest.

.SH OPTION

." Update options as and when new features are added.
.TP
.B -a
feature A
.TP
.B -b
feature B
.TP
.BI -f " filename"
Do something with
.B filename

.SH AUTHOR
Shanthanu S Rai <shanthanu.s.rai9@gmail.com>
